apiVersion: batch/v1
kind: Job
metadata:
  name: auth-service-migrate
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "1"
spec:
  backoffLimit: 2
  ttlSecondsAfterFinished: 600
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: ghcr.io/shinjon101/ticketing-auth-service:sha-0d175ed
          command: ["node", "dist/db/migrate.js"]
          envFrom:
            - secretRef: { name: auth-service-secrets }