apiVersion: v1
kind: ConfigMap
metadata:
  name: inventory-service-config
data:
  NODE_ENV: "production"
  PORT: "4006"
  LOG_LEVEL: "info"
  KAFKA_BROKERS: "kafka:9092"
  REDIS_URL: "redis://redis:6379"